version: "3"
include:
  - proxy.yaml

x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always 

services:
  db:
    image: mysql:8 
    networks:
      backend:
        ipv4_address: 172.20.0.10

    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" 
#    ports: ["3306:3306"]  
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    
    depends_on: ["db"]
    
    networks:
      backend:
        ipv4_address: 172.20.0.5
    
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
#    ports: ["5000:5000"]
