#version: "3"
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopp
services:
  mysql:
    image: mysql:8 
  #  networks: ["docker network"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" 
    ports: ["3306:3306"]  
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on: ["mysql"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    ports: ["5000:5000"]
  #  networks: ["docker network"]
#networks:
 # docker network:
    #name: docker network