version: "3"

services:
  db:
    image: mysql:8 
  #  networks: ["docker network"]

    env_file:
     - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" 
    ports: ["3306:3306"]  
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on: ["db"]

    env_file:
     - .env
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    ports: ["5000:5000"]
  #  networks: ["docker network"]
#networks:
 # docker network:
    #name: docker network